# Generated by Django 5.1.6 on 2025-08-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instructores", "0001_initial"),
        ("programas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("word", "Word"),
                            ("excel", "Excel"),
                            ("imagen", "Imagen"),
                            ("otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("archivo", models.FileField(upload_to="materiales/")),
                ("palabras_clave", models.TextField(blank=True, null=True)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="instructores.instructor",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programas.programa",
                    ),
                ),
            ],
        ),
    ]
