# Generated by Django 5.1.6 on 2025-08-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="archivo",
            field=models.FileField(blank=True, null=True, upload_to="materiales/"),
        ),
        migrations.AlterField(
            model_name="material",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="material",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PDF", "PDF"),
                    ("Word", "Word"),
                    ("Excel", "Excel"),
                    ("Imagen", "Imagen"),
                    ("Otro", "Otro"),
                ],
                max_length=50,
            ),
        ),
    ]
